language: php
php:
  - 7.1.23
services:
- mysql
before_install:
  -  mysql -e 'CREATE DATABASE testdata;'
install:
  - composer install
  - cp .env.test .env
  - php bin/console doctrine:schema:create

script:
  - php bin/phpunit
