version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
    - 3307:3306
    volumes:
    - ~/symfony-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}

  nginx:
    build: .docker/nginx
    volumes:
      - .docker/nginx/symfony.conf:/etc/nginx/sites-enabled/symfony.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/symfony
    links:
      - php
    depends_on:
      - php
    ports:
      - 8080:80

  php:
    build: .docker/php
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/symfony

